### ISSUE TITLE
org.gnome.Platform//3.36 is end-of-life

### ISSUE THREAD

**Issue by Mershl** [flathub/io.gitlab.jstest_gtk.jstest_gtk#2]
Flatpak now starts showing:
```
Info: org.gnome.Platform//3.36 is end-of-life, with reason:
   The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   io.gitlab.jstest_gtk.jstest_gtk
```

**Comment by Mershl** [comment]
Hi @Grumbel, thank you very much for your lightning fast commit. However the update is not yet live on flathub. How are updates to flathub usually triggered?

**Comment by Grumbel** [comment]
Builds are triggered on each push request, you can view the current one at:

https://flathub.org/builds/#/builders/32/builds/48113

There was an issue with the submodule that I fixed now.

**Comment by Grumbel** [comment]
v0.1.0-112-ga406c02 is now availabe on https://flathub.org/apps/details/io.gitlab.jstest_gtk.jstest_gtk
